HomWork Dao - Service
mate-academy/jv-dao-service pull request #234
Opened 2022-05-03 13:04 UTC by yuriikozar

Solution + Checkstyle
v1

2022-05-03 14:09 UTC, irynahrynda commented on src/main/java/mate/jdbc/dao/DriverDao.java
> +    Driver create(Driver manufacturer);
```suggestion
    Driver create(Driver driver);
```

2022-05-03 14:17 UTC, irynahrynda approved these changes

2022-05-03 15:35 UTC, Sofasmile requested changes

2022-05-03 15:35 UTC, Sofasmile commented on src/main/java/mate/jdbc/service/DriverService.java
> +    Optional<Driver> get(Long id);
```suggestion
    Driver get(Long id);
```
на рівні сервісу потрібно повертати напряму об'єкт

2022-05-03 15:35 UTC, Sofasmile commented on src/main/java/mate/jdbc/service/ManufacturerService.java
> +    Optional<Manufacturer> get(Long id);
same here

2022-05-03 15:44 UTC, Sofasmile requested changes

2022-05-03 15:44 UTC, Sofasmile commented on src/main/java/mate/jdbc/service/ManufacturerServiceImpl.java
> +                new NoSuchElementException("Couldn't get driver by id " + id));
```suggestion
                new NoSuchElementException("Couldn't get manufacturer by id " + id));
```

2022-05-04 06:42 UTC, Sofasmile approved these changes

2024-02-15 18:24 UTC, closed without merging