hw-dao-service
mate-academy/jv-dao-service pull request #301
Opened 2022-07-04 16:49 UTC by TymurTsvietkov

2022-07-04 19:50 UTC, Zinchuk-Yevhenii-Mate reviewed
Давай трішки покращимо твій код

2022-07-04 19:50 UTC, Zinchuk-Yevhenii-Mate commented on src/main/java/mate/jdbc/service/impl/ManufacturerServiceImpl.java
> +            throw new RuntimeException("Can`t find account with id: " + id);
```suggestion
            throw new RuntimeException("Can`t find manufacturer with id: " + id);
```

2022-07-04 20:08 UTC, Zinchuk-Yevhenii-Mate approved these changes
Молодець!)

2022-07-05 09:11 UTC, dSkarzh requested changes
Well done! Minor improvements can be made

2022-07-05 09:11 UTC, dSkarzh commented on src/main/java/mate/jdbc/service/impl/ManufacturerServiceImpl.java
> +        return manufacturer.get();
```suggestion
        return manufacturerDao.get(id).orElseThrow(// some exception with informative message);
```
better way to do the same as you did

2022-07-05 09:11 UTC, dSkarzh commented on src/main/java/mate/jdbc/service/impl/DriverServiceImpl.java
> +        return driver.get();
`orElseThrow()`

2022-07-05 09:51 UTC, dSkarzh approved these changes

2025-10-28 15:20 UTC, closed without merging