Jv dao service
mate-academy/jv-dao-service pull request #346
Opened 2022-09-08 13:49 UTC by fifahater

2022-09-08 14:29 UTC, JustElvis requested changes

2022-09-08 14:29 UTC, JustElvis commented on src/main/java/mate/jdbc/service/impl/ManufacturerServiceImpl.java
> +        return manufacturerDao.get(id);
```suggestion
    public Manufacturer get(Long id) {
        return manufacturerDao.get(id);
```
Read common mistakes. you must return not Otional in ServiceImpl

2022-09-08 14:29 UTC, JustElvis commented on src/main/java/mate/jdbc/service/impl/DriverServiceImpl.java
> +        return driverServiceDao.get(id);
```suggestion
    public Drive> get(Long id) {
        return driverServiceDao.get(id);
```
Read common mistakes. you must return not Otional in ServiceImpl

2022-09-08 14:29 UTC, JustElvis commented on src/main/java/mate/jdbc/dao/ManufacturerDaoImpl.java
> +public class ManufacturerDaoImpl implements ManufacturerService {
ManufacturerDaoImpl implements ManufacturerDao
You need to create layer Dao and layer Service.
You mix them. Why?

2022-09-08 14:29 UTC, JustElvis commented on src/main/java/mate/jdbc/dao/DriverServiceDaoImpl.java
> +public class DriverServiceDaoImpl implements DriverService {
the same

2022-09-08 15:22 UTC, JustElvis approved these changes

2022-09-09 06:50 UTC, Noct2000 requested changes

2022-09-09 06:50 UTC, Noct2000 commented on src/main/java/mate/jdbc/dao/impl/DriverServiceDaoImpl.java
> +                         = connection.prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {
```suggestion
                 PreparedStatement statement  = connection
                 .prepareStatement(query, Statement.RETURN_GENERATED_KEYS)) {
```

2022-09-09 06:50 UTC, Noct2000 commented on src/main/java/mate/jdbc/dao/impl/DriverServiceDaoImpl.java
> +                         = connection.prepareStatement(query)) {
```suggestion
                 PreparedStatement statement = connection
                 .prepareStatement(query)) {
```

2022-09-09 06:50 UTC, Noct2000 commented on src/main/java/mate/jdbc/dao/impl/DriverServiceDaoImpl.java
> +                         = connection.prepareStatement(query)) {
```suggestion
                 PreparedStatement statement = connection
                 .prepareStatement(query)) {
```

2022-09-09 07:52 UTC, Noct2000 approved these changes

2024-09-17 20:21 UTC, closed without merging