My-solution-task_dao_service
mate-academy/jv-dao-service pull request #459
Opened 2022-12-24 09:55 UTC by Swyatik19

2022-12-25 11:28 UTC, karma-o requested changes

2022-12-25 11:28 UTC, karma-o commented on src/main/java/mate/jdbc/dao/impl/DriverDaoImpl.java
> +            ResultSet generatedKeys = statement.getGeneratedKeys();
```suggestion
            ResultSet resultSet = statement.getGeneratedKeys();
```

2022-12-25 11:28 UTC, karma-o commented on src/main/java/mate/jdbc/Main.java
> +
you should call each service method here

2022-12-25 11:28 UTC, karma-o commented on src/main/java/mate/jdbc/model/Driver.java
> +@RequiredArgsConstructor
I think `Data` can replace all of these

2022-12-26 10:41 UTC, Rommelua approved these changes

2022-12-26 10:41 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/impl/DriverDaoImpl.java
> +                    + "from drivers table.", e);
```suggestion
            throw new DataProcessingException("Couldn't get a driver by id " + id, e);
```

2022-12-26 10:41 UTC, Rommelua commented on src/main/java/mate/jdbc/dao/impl/DriverDaoImpl.java
> +            return statement.executeUpdate() >= 1;
```suggestion
            return statement.executeUpdate() > 0;
```

2024-03-18 17:07 UTC, closed without merging