created model for a driver, dao for a driver, services for a driver
mate-academy/jv-dao-service pull request #477
Opened 2023-01-17 17:43 UTC by BusyhinD

and a manufacturer

2023-01-18 14:58 UTC, nacenik requested changes

2023-01-18 14:58 UTC, nacenik commented on src/main/java/mate/jdbc/Main.java
> +        Driver driver = new Driver();
Better to give a more understandable names for variables. Fix it in all places 
```suggestion
        Driver bob = new Driver();
```

2023-01-18 14:58 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +                    + " from drivers table.", e);
```suggestion
            throw new DataProcessingException("Couldn't get list of drivers from table.", e);
```

2023-01-18 14:58 UTC, nacenik commented on src/main/java/mate/jdbc/service/DriverServiceImpl.java
> +        return driverDao.get(id);
better to add `orElseThrow()` and throw NoSuchElementException with a message. Same for manufacture

2023-01-19 11:30 UTC, okuzan approved these changes
Good work :)

2024-02-13 20:59 UTC, closed without merging