done
mate-academy/jv-dao-service pull request #483
Opened 2023-01-21 20:10 UTC by diana-lomei

2023-01-22 16:11 UTC, nacenik requested changes
Don't forget to create your own branch.

2023-01-22 16:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +        String query = "INSERT INTO drivers(name, licenseNumber) VALUE(?, ?)";
```suggestion
        String query = "INSERT INTO drivers(name, license_number) VALUE(?, ?)";
```

2023-01-22 16:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +                driver.setId(id);
```suggestion
                driver.setId(generatedKeys.getObject(1, Long.class));
```

2023-01-22 16:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +        String licenseNumber = resultSet.getString("licenseNumber");
fix naming licenseNumber in all places

2023-01-22 16:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +    private Driver getDriver(ResultSet resultSet) throws SQLException {
private method should be after public

2023-01-22 16:11 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +            updateDriver.setLong(1, driver.getId());
```suggestion
            updateDriver.setLong(3, driver.getId());
```

2023-01-23 12:29 UTC, nacenik requested changes

2023-01-23 12:29 UTC, nacenik commented on src/main/resources/init_db.sql
> +                                          `id_deleted` tinyint NOT NULL DEFAULT '0',
```suggestion
                                          `is_deleted` tinyint NOT NULL DEFAULT '0',
```

2023-01-23 12:29 UTC, nacenik commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +public class DriverDaoImpl implements DriverDao {
Almost all methods are working with an error, cause you don't have the field `is_deleted` in your DB. Fix bug with naming

2023-01-23 16:49 UTC, andriy-shulepa requested changes

2023-01-23 16:49 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +        String query = "INSERT INTO drivers(name, license_number) VALUE(?, ?)";
```suggestion
        String query = "INSERT INTO drivers(name, license_number) VALUES(?, ?)";
```

2023-01-23 16:49 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +                + "WHERE id = ? AND is_deleted = FALSE;";
```suggestion
                + "WHERE id = ? AND is_deleted = FALSE";
```

2023-01-23 16:49 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/dao/DriverDaoImpl.java
> +
needless empty line

2023-01-23 16:49 UTC, andriy-shulepa commented on src/main/java/mate/jdbc/service/DriverServiceImpl.java
> +                new RuntimeException("Driver does not exist by id" + id));
RuntimeException is too general exception. use more concrete exception

2023-01-23 20:31 UTC, aleksandr-bevza approved these changes

2025-02-21 11:56 UTC, closed without merging