Solution
mate-academy/jv-dao-service pull request #678
Opened 2023-07-13 22:37 UTC by OlegMR0

2023-07-14 10:19 UTC, kozhukhovsky requested changes

2023-07-14 10:19 UTC, kozhukhovsky commented on src/main/java/mate/jdbc/Main.java
> +
```suggestion
```

2023-07-14 10:19 UTC, kozhukhovsky commented on src/main/java/mate/jdbc/dao/impl/DriverDaoImpl.java
> +            throw new DataProcessingException("Can't insert driver. " + driver.toString(), e);
```suggestion
            throw new DataProcessingException("Can't insert driver. " + driver, e);
            
```

When an object is cast to a String, whether it's the print method or string concatenation, toString doesn't need to be called explicitly, it's called by itself. Fix this everywhere, please.

2023-07-14 10:19 UTC, kozhukhovsky commented on src/main/java/mate/jdbc/service/impl/DriverServiceImpl.java
> +        return dao.get(id).get();
```suggestion
        return dao.get(id).orElseThrow(...);

```

if optional is empty, there will be an error.
In such places, you need to do .orElseThrow() and throw some kind of exception with a clear message.

2023-07-14 10:19 UTC, kozhukhovsky commented on src/main/java/mate/jdbc/service/impl/ManufacturerServiceImpl.java
> +        return dao.get(id).get();
same

2023-07-14 10:19 UTC, kozhukhovsky commented on src/main/resources/init_db.sql
> +
```suggestion
```

2023-07-16 10:00 UTC, Ivan95kos approved these changes
Great job

2023-07-16 11:25 UTC, closed without merging