dao vs service task done
mate-academy/jv-dao-service pull request #7
Opened 2021-05-11 11:23 UTC by mankokolya

2021-05-11 16:06 UTC, freedmanMain approved these changes

2021-05-17 08:13 UTC, RomanDubovskyi requested changes
you have git conflicts in PR

2021-05-17 08:13 UTC, RomanDubovskyi commented on src/main/java/mate/jdbc/dao/jdbc/DriverDaoImpl.java
> +                Statement statement = connection.createStatement()) {
why not prepared statement?

2021-05-17 08:29 UTC, mankokolya commented on src/main/java/mate/jdbc/dao/jdbc/DriverDaoImpl.java
> +                Statement statement = connection.createStatement()) {
Because we use static request

2021-05-17 08:29 UTC, mankokolya commented on pom.xml
> +        <dependency>
I used it in previos project

2021-05-17 09:59 UTC, mankokolya commented
Pushed to new branch 
https://github.com/mate-academy/jv-dao-service/pull/46

2021-05-17 10:00 UTC, closed without merging